# Generated by Django 4.1.2 on 2022-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('MK', 'Marketing'), ('NT', 'Nutrição'), ('DN', 'Design'), ('PS', 'Psicologia'), ('EC', 'Engenharia Civil'), ('FN', 'Fonoaudiologia'), ('EM', 'Engenharia Mecânica'), ('EP', 'Engenharia de Produção'), ('DS', 'Desenvolvedor de Software'), ('MT', 'Motorista'), ('AS', 'Assitente Social'), ('FM', 'Farmácia'), ('PR', 'Professor')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
