# Generated by Django 4.1.2 on 2022-11-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_vagas_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='carac_empresa',
            new_name='caracteristica_empresa',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
